spring:
  application:
    name: simplebank

  datasource:
    url: jdbc:mysql://localhost:3306/simplebank
    username: SA
    password: A1b@Cd3#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

logging:
  level:
    com.mchtcavas.simplebank: DEBUG
    root: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

application:
  bill-payment:
    operators:
      - turkcell
      - vodafone
      - turktelekom